CREATE DATABASE IF NOT EXISTS presensi_cv;

USE presensi_cv;

-- Tabel users
CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nim VARCHAR(20) UNIQUE NOT NULL,
 nama VARCHAR(100) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabel absensi
CREATE TABLE IF NOT EXISTS absensi (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nim VARCHAR(20) NOT NULL,
 nama VARCHAR(100) NOT NULL,
 waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 status VARCHAR(20) DEFAULT 'Hadir'
);